### ISSUE TITLE
wrong output processing in the 'in context learning' case

### ISSUE THREAD

**Issue by ernstklrb** [UW-Madison-Lee-Lab/LanguageInterfacedFineTuning#4]
Hi @yzeng58 , @UW-Madison-Lee-Lab ,

I think for the case of ICL the code referenced below does the wrong thing. It will extract the ground truth value of the _first_ example given in the prompt, instead of the answer that would be found after the _last_ @@@

https://github.com/UW-Madison-Lee-Lab/LanguageInterfacedFineTuning/blob/a1cb01fb3fa3c4c1124a95c15be9b9747d825680/classification/run_exps/run_exps_helper.py#L261

**Comment by yzeng58** [comment]
Hi @ernstklrb,

Thank you for reaching out to us and bringing this issue to our attention. Our team has thoroughly investigated the problem you mentioned and we have discovered that this was due to multiple versions of code being available and the incorrect version being uploaded.

We have now corrected the issue and have tested the updated code. We are happy to report that the results are in line with what we have previously obtained.

Please let us know if there is anything else we can assist you with. We apologize for any inconvenience this may have caused.
