### ISSUE TITLE
load_data is not defined

### ISSUE THREAD

**Issue by NuiMrme** [UW-Madison-Lee-Lab/LanguageInterfacedFineTuning#5]
Hi and thank you for making the code available, I'm trying to run the classification with GPTJ and in the file run_gptj there is a call for load_data but it gives **"name 'load_data' is not defined"** 

Could you please point out what I'm missing ?
Thanks in advance

**Comment by yzeng58** [comment]
Dear NuiMrme,

Thank you for reaching out.

I am assuming that you are compiling the file `classification/run_exps/run_gptj.py`. In that case, the function `load_data` is actually imported from `classification/run_exps/run_exps_helper.py`.

I've double-checked and successfully run the classification/run_exps/run_gptj.py file on my end without any issues. If it's not too much trouble, could you please provide a bit more context or possibly share the code you're using to execute the script? This additional information could be incredibly helpful in assisting us to pinpoint the source of the issue.

Thank you for your patience and cooperation on this matter.

Best regards,
Yuchen Zeng on behalf of all the authors

**Comment by yzeng58** [comment]
Dear NuiMrme,

Since there has been no further communication on the load_data issue, we will be closing this thread to keep our issues log up to date. Should you have any new inquiries or require assistance in the future, please feel free to open a new issue.

Best regards,
Yuchen Zeng on behalf of all the authors
